"""empty message

Revision ID: 50d88e837430
Revises: 
Create Date: 2025-10-30 19:57:27.788163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50d88e837430'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('heartbeat_interval_s', sa.Integer(), server_default=sa.text('15'), nullable=False),
    sa.Column('online_threshold_s', sa.Integer(), server_default=sa.text('45'), nullable=False),
    sa.Column('offline_threshold_s', sa.Integer(), server_default=sa.text('120'), nullable=False),
    sa.Column('pagination_size', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('max_posts_per_bot', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('notify_rights_error', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notify_failures', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('retention_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('retention_days', sa.Integer(), server_default=sa.text('180'), nullable=False),
    sa.Column('default_drain_mode', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_index(op.f('ix_settings_settings_is_current'), 'settings', ['is_current'], unique=False)
    op.create_index(op.f('ix_settings_settings_name'), 'settings', ['name'], unique=True)
    op.create_index('uq_settings_is_current', 'settings', ['is_current'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_users_username'), 'users', ['username'], unique=True)
    op.create_table('bots',
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('server_ip', sa.String(length=64), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('self_destruction', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deactivated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('settings_id', sa.UUID(), nullable=True),
    sa.Column('max_posts', sa.BigInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], name=op.f('fk_bots_settings_id_settings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bots'))
    )
    op.create_index(op.f('ix_bots_bots_bot_id'), 'bots', ['bot_id'], unique=True)
    op.create_index(op.f('ix_bots_bots_deactivated'), 'bots', ['deactivated'], unique=False)
    op.create_index(op.f('ix_bots_bots_server_ip'), 'bots', ['server_ip'], unique=False)
    op.create_index(op.f('ix_bots_bots_settings_id'), 'bots', ['settings_id'], unique=False)
    op.create_index(op.f('ix_bots_bots_username'), 'bots', ['username'], unique=False)
    op.create_index('uq_bots_server_ip_active', 'bots', ['server_ip'], unique=True, postgresql_where=sa.text('deactivated = false'))
    op.create_table('groups',
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('last_post_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_bot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_bot_id'], ['bots.id'], name=op.f('fk_groups_assigned_bot_id_bots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_index(op.f('ix_groups_groups_assigned_bot_id'), 'groups', ['assigned_bot_id'], unique=False)
    op.create_index(op.f('ix_groups_groups_tg_chat_id'), 'groups', ['tg_chat_id'], unique=True)
    op.create_index(op.f('ix_groups_groups_type'), 'groups', ['type'], unique=False)
    op.create_table('posts',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('target_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('source_channel_username', sa.String(length=255), nullable=False),
    sa.Column('source_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('source_message_id', sa.BigInteger(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('count_attempts', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('target_attempts', sa.BigInteger(), nullable=False),
    sa.Column('delete_last_attempt', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pin_after_post', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('num_attempt_for_pin_post', sa.BigInteger(), nullable=True),
    sa.Column('pause_between_attempts_s', sa.BigInteger(), server_default=sa.text('60'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_posts_bot_id_bots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_posts_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_posts_bot_id'), 'posts', ['bot_id'], unique=False)
    op.create_index(op.f('ix_posts_posts_group_id'), 'posts', ['group_id'], unique=False)
    op.create_index('uq_posts_active_per_group', 'posts', ['group_id'], unique=True, postgresql_where=sa.text("status IN ('active','paused','error')"))
    op.create_index('uq_posts_group_source', 'posts', ['group_id', 'source_channel_username', 'source_message_id'], unique=True)
    op.create_table('postattempts',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_postattempts_bot_id_bots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_postattempts_group_id_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_postattempts_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postattempts'))
    )
    op.create_index(op.f('ix_postattempts_postattempts_bot_id'), 'postattempts', ['bot_id'], unique=False)
    op.create_index(op.f('ix_postattempts_postattempts_group_id'), 'postattempts', ['group_id'], unique=False)
    op.create_index(op.f('ix_postattempts_postattempts_post_id'), 'postattempts', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postattempts_postattempts_post_id'), table_name='postattempts')
    op.drop_index(op.f('ix_postattempts_postattempts_group_id'), table_name='postattempts')
    op.drop_index(op.f('ix_postattempts_postattempts_bot_id'), table_name='postattempts')
    op.drop_table('postattempts')
    op.drop_index('uq_posts_group_source', table_name='posts')
    op.drop_index('uq_posts_active_per_group', table_name='posts', postgresql_where=sa.text("status IN ('active','paused','error')"))
    op.drop_index(op.f('ix_posts_posts_group_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_posts_bot_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_groups_groups_type'), table_name='groups')
    op.drop_index(op.f('ix_groups_groups_tg_chat_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_groups_assigned_bot_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index('uq_bots_server_ip_active', table_name='bots', postgresql_where=sa.text('deactivated = false'))
    op.drop_index(op.f('ix_bots_bots_username'), table_name='bots')
    op.drop_index(op.f('ix_bots_bots_settings_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_bots_server_ip'), table_name='bots')
    op.drop_index(op.f('ix_bots_bots_deactivated'), table_name='bots')
    op.drop_index(op.f('ix_bots_bots_bot_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_users_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_settings_is_current', table_name='settings', postgresql_where=sa.text('is_current = true'))
    op.drop_index(op.f('ix_settings_settings_name'), table_name='settings')
    op.drop_index(op.f('ix_settings_settings_is_current'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
